export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const EMPLOYEE_CREATE_IN_PROGRESS = 'EMPLOYEE_CREATE_IN_PROGRESS';
export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAILED = 'EMPLOYEE_CREATE_FAILED';

export const EMPLOYEE_FETCH_IN_PROGRESS = 'EMPLOYEE_FETCH_IN_PROGRESS';
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const EMPLOYEE_FETCH_FAILED = 'EMPLOYEE_FETCH_FAILED';

export const EMPLOYEE_FETCH_LISTENER_IN_PROGRESS =
  'EMPLOYEE_FETCH_LISTENER_IN_PROGRESS';
export const EMPLOYEE_FETCH_LISTENER_SUCCESS =
  'EMPLOYEE_FETCH_LISTENER_SUCCESS';
export const EMPLOYEE_FETCH_LISTENER_FAILED = 'EMPLOYEE_FETCH_LISTENER_FAILED';

export const EMPLOYEE_UPDATE_IN_PROGRESS = 'EMPLOYEE_UPDATE_IN_PROGRESS';
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS';
export const EMPLOYEE_UPDATE_FAILED = 'EMPLOYEE_UPDATE_FAILED';

export const EMPLOYEE_REMOVE_IN_PROGRESS = 'EMPLOYEE_REMOVE_IN_PROGRESS';
export const EMPLOYEE_REMOVE_SUCCESS = 'EMPLOYEE_REMOVE_SUCCESS';
export const EMPLOYEE_REMOVE_FAILED = 'EMPLOYEE_REMOVE_FAILED';
